$(function(){
	$(".right2,.right3,.right4,.right6,.right7").mouseenter(function(){
		$(this).children().eq(1).animate({
			left:-90,
			queue:false
		});
	});
	$(".right2,.right3,.right4,.right6,.right7").mouseleave(function(){
		$(this).children().eq(1).animate({
			left:0,
			queue:false
		});
	});
	$(".right1").mouseenter(function(){
		$(this).children().eq(1).animate({
			left:-260,
			queue:false
		},100);
	});
	$(".right1").mouseleave(function(){
		$(this).children().eq(1).animate({
			left:50,
			queue:false
		},100);
	});
	$(".right5").mouseenter(function(){
		$(this).children().eq(1).animate({
			left:-132,
			queue:false
		},100);
	});
	$(".right5").mouseleave(function(){
		$(this).children().eq(1).animate({
			left:50,
			queue:false
		},100);
	});
})